### ISSUE TITLE
[BUG] visual editor not supported

### ISSUE THREAD

**Issue by kimbo1st** [flixlix/power-flow-card-plus#556]
**Describe the bug**

**To Reproduce**
1. Add Card
2. Has already some preconfigured entities
3. It already states the error: _a.entries is not a function. (In '_a.entries()', '_a.entries' is undefined)
4. Yaml code editor can be done but still the error appears.

**Expected behavior**
Visual editor to be available

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: 
 - The error is as well as in the chrome browser as in the HA app.

**Additional context**
Latest HA version 2024.4.3 running in Docker.
Also updated to he last version of your app.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by kimbo1st** [comment]
> Do you have card mod installed?

Yes I have

**Comment by flixlix** [comment]
What happens if you uninstall it?

(Make sure to clear your browser cache after uninstalling and refreshing the page)

**Comment by AshaiRey** [comment]
Rename card-mod.js to something else
Clear files from browser cache
Close browser
Reopen brower

This will fix the issue

**Comment by Chimpepe** [comment]
Same Issue here, no card mod installed

**Comment by kimbo1st** [comment]
> Rename card-mod.js to something else Clear files from browser cache Close browser Reopen brower
> 
> This will fix the issue

Will this stop card-mod to work or it just replaces it to a newer version?

**Comment by AminShAT** [comment]
Many problems after upgrade from v1.8 to v2.0 here:

Settings of individual entries like changing name or icon via GUI has no effect, only works in yaml.

Can't add the EVCS of Victron anymore. Used the same sensor, that worked in v1.8.

**Comment by flixlix** [comment]
@AminShAT 
Check #551

**Comment by flixlix** [comment]
@Chimpepe this is because your config still contains `individual1` and `individual2`, which are now not supported anymore.
Please remove these and add them with the ui editor

**Comment by Chimpepe** [comment]
Okay, removed these two individual but still no visual editor 

![image](https://github.com/flixlix/power-flow-card-plus/assets/8383232/296d7159-fcff-4e00-bd49-777e8f3873de)

**Comment by flixlix** [comment]
You might need to restart HA and clear your cache for the changes to apply

**Comment by PottiMc** [comment]
Card-Mod was not the problem. Browser mod was also not the problem here. I restarted after every single uninstall and cleared the cache. It could be Kiosk Mode oder UI Lovelace Minimalist. Unfortunately I uninstalled them both in one step.

Now the GUI is working fine for me in a NEW Power Flow Card Plus.

**Comment by flixlix** [comment]
@PottiMc can you try reinstalling each card one by one and see which one has the conflict?

**Comment by PottiMc** [comment]
It is "UI Lovelace Minimalist" which is messing up. Installed all one by one and have browser-mod, kiosk-mode and card-mod running again. 
The error occured when installing UI Lovelace Minimalist.

**Comment by flixlix** [comment]
@PottiMc thank you very much for the help.
I was not very familiar with this custom plugin.

I noticed they placed the card-mod source js inside the repo, although it does seem like bad practice to simply place the js from another card inside your own repo (as you can see in this case, files are not kept up to date, causing bugs and frustration to us all...).

Anyway, I created a PR that aims to fix this by updating the card-mod file to version 3.4.3 (latest)

https://github.com/UI-Lovelace-Minimalist/UI/pull/1489

For now I'm closing this issue, because this is a conflict with a third party card and not related to power-flow-card-plus (any card that has `entities` as an object will get this error). Plus I don't know how long it would take to merge the PR I created.

Thank you once again for the help and sorry for the inconvenience
